# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eac97c1258248e5b048d1b76f93043240479261fa0a679597c5262fc3dd99aeeda6e7752674e595e812feedef284867865fbf127bf99cf19e45fe60ea887762f

test:
  secret_key_base: 1d2f2318eaf7fd67842315c06c8f247c4dab394713788adfdf122f244c8e837821ff97b3dbea7870fa1a00a92c8e26421c8644b128c8dffb13085aace9c1fc6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
